### ISSUE TITLE
Some minor problems to create Yocto recipe

### ISSUE THREAD

**Issue by nefethael** [naggety/picotts#3]
Hello, I'm trying to create a recipe for Yocto distro build tool, and I'd some problems with picotts:

1- Is it possible to remove `/.pc` folder which corresponds to internal Quilt tool directory?
It conflicts with Yocto in case there is another patch over already applied ones.

2- In `/pico/Makefile.am`, there are some wildcards for lang (ie `lang/de-DE*.bin`) and it seems autotools don't handle them?
One solution is to list every files instead

<details>
  <summary>Here's my current Yocto recipe</summary>
  
  ```
  LICENSE = "Apache-2.0"
  LIC_FILES_CHKSUM = "file://pico_resources/MODULE_LICENSE_APACHE2;md5=d41d8cd98f00b204e9800998ecf8427e"
  
  SRC_URI = "git://github.com/naggety/picotts"
  
  SRC_URI += "file://0011-Remove-unsupported-wildcard-in-makefile.patch"
  
  DEPENDS = "popt"
  
  PV = "1.0+git${SRCPV}"
  SRCREV = "e3ba46009ee868911fa0b53db672a55f9cc13b1c"
  
  S = "${WORKDIR}/git"
  
  AUTOTOOLS_SCRIPT_PATH = "${S}/pico"
  
  CFLAGS_append = " -I${S}/pico/lib"
  
  inherit autotools pkgconfig
  
  do_unpack[postfuncs] += "do_clean_pc"
  do_clean_pc() {
      rm -r ${S}/.pc
  }
  
  FILES_${PN} += "${datadir}"
  
  ```
</details>

**Comment by ihuguet** [comment]
Hello,

I'm not sure about the convenience of removing .pc directory. I have never used Quilt, but as far as I understand, this patches can also be seen as some kind of "history" of the last changes. Given that we don't have the Git history, they can be useful.

I neither have used Yocto, but for example in Buildroot, as part of the download-extract-build-install process, in the extract step you can take a single folder from the downloaded package. Could you use just "pico" folder and ignore the rest in Yocto?

With the wildcard in Makefile.am I have no problem at all, neither building targeting my computer nor cross-compiling with Buildroot.

Which errors do you get in both cases?

**Comment by nefethael** [comment]
@naggety Hi,

For Makefile.am, I have `No rule to make target lang/de-DE*.bin` error. I'm not sure what's the problem but in autotools documentation, it says it's not supported [here](https://www.gnu.org/software/automake/manual/html_node/Wildcards.html). Maybe in both Buildroot and native compilation there are some autotools customization? 

To fix this I introduced a Makefile.am patch (0011-Remove-unsupported-wildcard-in-makefile.patch) but it cannot be applied in case .pc folder already exists. Yocto uses quilt to patch sources, but as it find .pc folder, he messes do_patch process and leaves sources in bad shape so compilation is impossible then.

Yocto recipe I provided in previous message works fine but it's a bit hackich so I can understand you prefer to close this ticket.

Best regards,
Vincent

**Comment by ihuguet** [comment]
Regarding the wildcard, you seem to be right that shouldn't be used. I think it may not work in your system, and yes in mine, because of different versions of 'make', or maybe the shell. I'm using GNU make and Bash, which ones are you using? About the shell, Yocto scripts use a specific shebang like #!/bin/sh?

In any case, I will fix it, can you provide me your file 0011-Remove-unsupported-wildcard-in-makefile.patch to see your solution?

I still don't know what to do with .pc folder. It seems that deleting it wouldn't be bad in anyway, and you always can recover it from the git history. However, what to do then with "debian" folder? Can you ask in Yocto forums, IRC or whatever what to do in this cases?

**Comment by nefethael** [comment]
Here's what I use :

<details>
    <summary>0011-Remove-unsupported-wildcard-in-makefile.patch</summary>

    Index: git/pico/Makefile.am
    ===================================================================
    --- git.orig/pico/Makefile.am
    +++ git/pico/Makefile.am
    @@ -74,12 +74,19 @@ libttspico_la_LIBADD = -lm
     
     picolangdir = $(datadir)/pico/lang
     picolang_DATA = \
    -    lang/de-DE*.bin \
    -    lang/en-GB*.bin \
    -    lang/en-US*.bin \
    -    lang/es-ES*.bin \
    -    lang/fr-FR*.bin \
    -    lang/it-IT*.bin
    +    lang/de-DE_gl0_sg.bin \
    +    lang/de-DE_ta.bin     \
    +    lang/en-GB_kh0_sg.bin \
    +    lang/en-GB_ta.bin     \
    +    lang/en-US_lh0_sg.bin \
    +    lang/en-US_ta.bin     \
    +    lang/es-ES_ta.bin     \
    +    lang/es-ES_zl0_sg.bin \
    +    lang/fr-FR_nk0_sg.bin \
    +    lang/fr-FR_ta.bin     \
    +    lang/it-IT_cm0_sg.bin \
    +    lang/it-IT_ta.bin
    +
     
     bin_PROGRAMS = pico2wave
     pico2wave_SOURCES = \

</details>

It could be also replaced by `$(wildcard lang/de-DE*.bin)` I think.

I'm not sure how make and shell are handled by Yocto. 

If I understand it correctly, you applied patches from debian folder to main sources? If so, I think you can leave debian folder as-is, and just remove .pc quilt internal directory?

**Comment by ihuguet** [comment]
I've modified Makefile.am to list every file instead using the wildcard (269a02af9ad5a138581466d04d7bec418c5625f5). Using $(wildcard) is also unsupported according the link you have posted.

Patches seems to be applied from debian folder, but I don't know exactly how because I didn't do it. What you see is extracted directly from the .deb package with just a few fixes made by me. I don't know how it was generated the debian package or applied the patches.

**Comment by ihuguet** [comment]
I've been playing a bit with Quilt and now understand what is .pc folder for, and how Quilt works (more or less). I think that deleting .pc folder is a good thing because changes made and commited with Git will make reverting those patches not working, so .pc folder will be useless.

Changed in [21089d22](https://github.com/naggety/picotts/commit/21089d223e177ba3cb7e385db8613a093dff74b5)
